##
## EPITECH PROJECT, 2019
## PSU_navy_2019
## File description:
## Makefile Librairy
##

SILENT = @

all:
	$(SILENT)make -C utils/
	$(SILENT)make -C printf/

clean:
	$(SILENT)make -C utils/ clean
	$(SILENT)make -C printf/ clean
	$(SILENT)rm -rf objects/

fclean:
	$(SILENT)make -C utils/ fclean
	$(SILENT)make -C printf/ fclean
	$(SILENT)rm -rf objects/
	$(SILENT)rm -rf include/

re:
	$(SILENT)make -C utils/ re
	$(SILENT)make -C printf/ re